dist: focal
os: linux

language: python
python:
  - "3.7"

# install system dependencies here with apt-get.
before_install:
  - sudo ./provision/debian.sh
  - python -m pip install --upgrade pip setuptools wheel

# install python dependencies including this package in the travis
# virtualenv
install:
  - ./provision/python.sh;
  - pip install .

# commands to run the testing suite. if any of these fail, travic lets us know
script:
  - cd tests && make && cd -
  - nosetests --with-coverage --cover-package=textract
  - cd tests && pytest && cd -
  - cd docs && make html && cd -;

# commands to run after the tests successfully complete
after_success:
  - coveralls
